# Generated by Django 4.1 on 2022-09-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(help_text='Ad\nName\nИмя', max_length=256, verbose_name='Ad\nName\nИмя')),
                ('child_surname', models.CharField(max_length=256, verbose_name='Soyad\nSurname\nФамилия')),
                ('child_age', models.PositiveSmallIntegerField(help_text='Yaş / Age / ВОЗРАСТ', verbose_name='Yaş / Age / ВОЗРАСТ')),
                ('diseases_allergy', models.CharField(default='YOK\nNone\nНету', help_text='Hastalık / Alerji\nDiseases/ Allergy\nЗаболевание / Аллергия', max_length=256, verbose_name='Hastalık / Alerji\nDiseases/ Allergy\nЗаболевание / Аллергия')),
                ('parents_name', models.CharField(help_text='Ad\nName\nФамилия', max_length=256, verbose_name='Ad\nName\nИмя')),
                ('parents_surname', models.CharField(max_length=256, verbose_name='Soyad\nSurname\nФамилия')),
                ('phone1', models.CharField(help_text='+X(XXX)XXX-XXX-XXX', max_length=20, unique=True, verbose_name='Tel No\n Phone number\n Тел. номер')),
                ('phone2', models.CharField(help_text='+X(XXX)XXX-XXX-XXX', max_length=20, unique=True, verbose_name='Tel No\n Phone number\n Тел. номер')),
                ('room_number', models.CharField(help_text='Oda no\n Room number\n Номер комнаты', max_length=5, verbose_name='Oda no\n Room number\n Номер комнаты')),
                ('permission_leave', models.BooleanField(default=False, help_text='Yalnız Gidebilir mi ?\nCan child leave the club alone ?\nМожет ли ребенок покинуть клуб один?', verbose_name='Yalnız Gidebilir mi ?')),
                ('permission_foto', models.BooleanField(default=True, verbose_name='Foto izin\nРазрещение на фотографии')),
                ('permission_activiti', models.BooleanField(default=True, verbose_name='Atöliyeye katılım izin\n Разщенение на мастер-класс')),
                ('check_out_date', models.DateField(help_text='Çıkış Tarihi/\nHotel Check-out Date /\nДата выезда из отеля', verbose_name='Çıkış Tarihi/\nHotel Check-out Date /\nДата выезда из отеля')),
            ],
            options={
                'verbose_name': 'Çocuk Kayıt.\nChild Registration\nРегистрация ребенка',
                'verbose_name_plural': "Çocuk Kayıtlar.\nChild Registration's\nРегистрации детей",
                'ordering': ['-room_number'],
            },
        ),
    ]
