# Generated by Django 4.1.2 on 2022-10-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="%Y/%m/%d",
                        verbose_name="Photo\nResimi\nФотография",
                    ),
                ),
                (
                    "child_name",
                    models.CharField(max_length=256, verbose_name="Ad\nName\nИмя"),
                ),
                (
                    "child_surname",
                    models.CharField(
                        max_length=256, verbose_name="Soyad\nSurname\nФамилия"
                    ),
                ),
                (
                    "child_age",
                    models.PositiveSmallIntegerField(
                        verbose_name="Yaş / Age / ВОЗРАСТ"
                    ),
                ),
                (
                    "diseases_allergy",
                    models.CharField(
                        default="YOK\nNone\nНету",
                        max_length=256,
                        verbose_name="Hastalık / Alerji\nDiseases/ Allergy\nЗаболевание / Аллергия",
                    ),
                ),
                (
                    "parents_name",
                    models.CharField(max_length=256, verbose_name="Ad\nName\nИмя"),
                ),
                (
                    "parents_surname",
                    models.CharField(
                        max_length=256, verbose_name="Soyad\nSurname\nФамилия"
                    ),
                ),
                (
                    "parents_email",
                    models.EmailField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Email\n Э-почта",
                    ),
                ),
                (
                    "phone1",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Tel No\n Phone number\n Тел. номер +X(XXX)XXX-XXX-XXX",
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Tel No\n Phone number\n Тел. номер +X(XXX)XXX-XXX-XXX",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        max_length=5,
                        verbose_name="Oda no\n Room number\n Номер комнаты",
                    ),
                ),
                (
                    "permission_leave",
                    models.CharField(
                        choices=[("YES", "YES"), ("NO", "NO")],
                        max_length=3,
                        verbose_name="Yalnız Gidebilir mi ?",
                    ),
                ),
                (
                    "permission_photo",
                    models.CharField(
                        choices=[("YES", "YES"), ("NO", "NO")],
                        max_length=3,
                        verbose_name="Foto izin\nРазрещение на фотографии",
                    ),
                ),
                (
                    "permission_activity",
                    models.CharField(
                        choices=[("YES", "YES"), ("NO", "NO")],
                        max_length=3,
                        verbose_name="Atöliyeye katılım izin\n Разщенение на мастер-класс",
                    ),
                ),
                (
                    "check_out_date",
                    models.DateField(
                        verbose_name="Çıkış Tarihi/\nHotel Check-out Date /\nДата выезда из отеля"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
            ],
            options={
                "verbose_name": "Çocuk Kayıt.\nChild Registration\nРегистрация ребенка",
                "verbose_name_plural": "Çocuk Kayıtlar.\nChild Registration's\nРегистрации детей",
                "ordering": ["check_out_date"],
            },
        ),
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256,
                        verbose_name="Name Surname İsim Soysism Имя Фамилия",
                    ),
                ),
                ("email", models.EmailField(max_length=256, verbose_name="E-mail")),
                (
                    "phone",
                    models.CharField(
                        max_length=30, verbose_name="Phone Tel No Номер телефона"
                    ),
                ),
                (
                    "message",
                    models.TextField(max_length=5000, verbose_name="Message Сообщение"),
                ),
                ("date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Geri Dönüşüm",
                "verbose_name_plural": "Geri Dönüşümler",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="Isim\n Имя\n Name"),
                ),
                (
                    "surname",
                    models.CharField(
                        max_length=30, verbose_name="Soyisim\n Фамилия\n Surname"
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        verbose_name="Yaş\n Age\n Возвраст"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="%Y/%m/%d",
                        verbose_name="Photo\nResimi\nФотография",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("DIR", "Departman Animasiyon Müdürü"),
                            ("SEF", "Animasiyon Şef"),
                            ("ASEF", "Animasiyon Şef Asistan"),
                            ("ANI", "Animatör"),
                        ],
                        max_length=100,
                        verbose_name="Position\n Должность",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=256, verbose_name="Tel No:\n Номер телефона"
                    ),
                ),
                ("start_work", models.DateField(auto_now_add=True)),
                ("end_work", models.DateField(blank=True, null=True)),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
            ],
            options={
                "verbose_name": "Personal Kayıt.\nPersonal Registration\nРегистрация персонала",
                "verbose_name_plural": "Personal Kayıtlar.\nPersonal Registration's\nРегистрации персонала",
                "ordering": ["name"],
            },
        ),
    ]
