# Generated by Django 4.1.2 on 2022-10-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="Isim\n Имя\n Name"),
                ),
                (
                    "surname",
                    models.CharField(
                        max_length=30, verbose_name="Soyisim\n Фамилия\n Surname"
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        verbose_name="Yaş\n Age\n Возвраст"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="%Y/%m/%d",
                        verbose_name="Photo\nResimi\nФотография",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("DIR", "Departman Animasiyon Müdürü"),
                            ("SEF", "Animasiyon Şef"),
                            ("ASEF", "Animasiyon Şef Asistan"),
                            ("ANI", "Animatör"),
                        ],
                        max_length=100,
                        verbose_name="Position\n Должность",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=256, verbose_name="Tel No:\n Номер телефона"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
            ],
            options={
                "verbose_name": "Personal Kayıt.\nPersonal Registration\nРегистрация персонала",
                "verbose_name_plural": "Personal Kayıtlar.\nPersonal Registration's\nРегистрации персонала",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={
                "ordering": ["check_out_date"],
                "verbose_name": "Çocuk Kayıt.\nChild Registration\nРегистрация ребенка",
                "verbose_name_plural": "Çocuk Kayıtlar.\nChild Registration's\nРегистрации детей",
            },
        ),
        migrations.AddField(
            model_name="registration",
            name="child_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="%Y/%m/%d",
                verbose_name="Photo\nResimi\nФотография",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="slug",
            field=models.SlugField(default=1, unique=True, verbose_name="URL"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registration",
            name="check_out_date",
            field=models.DateField(
                verbose_name="Çıkış Tarihi/\nHotel Check-out Date /\nДата выезда из отеля"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="child_age",
            field=models.PositiveSmallIntegerField(verbose_name="Yaş / Age / ВОЗРАСТ"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="child_name",
            field=models.CharField(max_length=256, verbose_name="Ad\nName\nИмя"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="diseases_allergy",
            field=models.CharField(
                default="YOK\nNone\nНету",
                max_length=256,
                verbose_name="Hastalık / Alerji\nDiseases/ Allergy\nЗаболевание / Аллергия",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="parents_name",
            field=models.CharField(max_length=256, verbose_name="Ad\nName\nИмя"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="permission_activiti",
            field=models.CharField(
                choices=[("YES", "YES"), ("NO", "NO")],
                max_length=3,
                verbose_name="Atöliyeye katılım izin\n Разщенение на мастер-класс",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="permission_foto",
            field=models.CharField(
                choices=[("YES", "YES"), ("NO", "NO")],
                max_length=3,
                verbose_name="Foto izin\nРазрещение на фотографии",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="permission_leave",
            field=models.CharField(
                choices=[("YES", "YES"), ("NO", "NO")],
                max_length=3,
                verbose_name="Yalnız Gidebilir mi ?",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="phone1",
            field=models.CharField(
                max_length=20,
                unique=True,
                verbose_name="Tel No\n Phone number\n Тел. номер +X(XXX)XXX-XXX-XXX",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="phone2",
            field=models.CharField(
                max_length=20,
                unique=True,
                verbose_name="Tel No\n Phone number\n Тел. номер +X(XXX)XXX-XXX-XXX",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="room_number",
            field=models.CharField(
                max_length=5, verbose_name="Oda no\n Room number\n Номер комнаты"
            ),
        ),
    ]
